table bears_vs_league
	lineageTag: 557189e5-b268-49c9-aa9e-135832dd7f17

	column season
		dataType: int64
		formatString: 0
		lineageTag: 0a5c3fe3-5d1e-4136-837e-62022528113c
		summarizeBy: sum
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column team
		dataType: string
		lineageTag: ecb31fc7-7fc1-4b4a-952f-0623adf2c4b6
		summarizeBy: none
		sourceColumn: team

		annotation SummarizationSetBy = Automatic

	column games_played
		dataType: int64
		formatString: 0
		lineageTag: d4ad65f0-34ef-4783-b50c-2e5dd93fcc45
		summarizeBy: sum
		sourceColumn: games_played

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: 23bf535e-033c-4987-bce5-e7731c9cd6f1
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	column losses
		dataType: int64
		formatString: 0
		lineageTag: b4590374-37af-4e97-a61c-86f9913e49fb
		summarizeBy: sum
		sourceColumn: losses

		annotation SummarizationSetBy = Automatic

	column win_pct
		dataType: double
		lineageTag: dfff1df1-4d1a-46c8-83d7-dc2cb5e80650
		summarizeBy: sum
		sourceColumn: win_pct

		annotation SummarizationSetBy = Automatic

	column points_per_game
		dataType: double
		lineageTag: a643f783-83d7-480a-a812-c1a1a488b173
		summarizeBy: sum
		sourceColumn: points_per_game

		annotation SummarizationSetBy = Automatic

	column points_allowed_per_game
		dataType: double
		lineageTag: 5d75a457-890e-4f9a-9532-c904aa02fa88
		summarizeBy: sum
		sourceColumn: points_allowed_per_game

		annotation SummarizationSetBy = Automatic

	column point_differential
		dataType: double
		lineageTag: 42254d4d-b054-4aea-a9d6-978235eafc69
		summarizeBy: sum
		sourceColumn: point_differential

		annotation SummarizationSetBy = Automatic

	column off_epa_per_play
		dataType: double
		lineageTag: 4d99d982-f3e1-4244-8f1a-9b8e97b56d71
		summarizeBy: sum
		sourceColumn: off_epa_per_play

		annotation SummarizationSetBy = Automatic

	column off_success_rate
		dataType: double
		lineageTag: 3c8ea6aa-b71e-4f19-9ee2-3e03fdfc1140
		summarizeBy: sum
		sourceColumn: off_success_rate

		annotation SummarizationSetBy = Automatic

	column off_third_down_pct
		dataType: double
		lineageTag: 4b298e39-fcec-4db5-b9aa-592d6a029184
		summarizeBy: sum
		sourceColumn: off_third_down_pct

		annotation SummarizationSetBy = Automatic

	column off_turnovers
		dataType: double
		lineageTag: 206e2f21-3530-445e-9e28-a47ac69794ea
		summarizeBy: sum
		sourceColumn: off_turnovers

		annotation SummarizationSetBy = Automatic

	column off_penalties
		dataType: double
		lineageTag: 2b692354-8f52-4826-9362-7f526acaef0c
		summarizeBy: sum
		sourceColumn: off_penalties

		annotation SummarizationSetBy = Automatic

	column def_epa_per_play_allowed
		dataType: double
		lineageTag: dccd7230-7cd6-4084-a888-5897860ec669
		summarizeBy: sum
		sourceColumn: def_epa_per_play_allowed

		annotation SummarizationSetBy = Automatic

	column def_success_rate_allowed
		dataType: double
		lineageTag: a15178c0-6831-4409-9717-a37f288ab3cb
		summarizeBy: sum
		sourceColumn: def_success_rate_allowed

		annotation SummarizationSetBy = Automatic

	column def_third_down_pct_allowed
		dataType: double
		lineageTag: 9b9b7c91-5259-49ec-8ff4-053fdc5c86a0
		summarizeBy: sum
		sourceColumn: def_third_down_pct_allowed

		annotation SummarizationSetBy = Automatic

	column def_takeaways
		dataType: double
		lineageTag: 1eadb9f2-02c6-4d3f-ba68-e709f4674594
		summarizeBy: sum
		sourceColumn: def_takeaways

		annotation SummarizationSetBy = Automatic

	column turnover_margin
		dataType: double
		lineageTag: 13d798a6-5321-4b93-8304-95c88b627f31
		summarizeBy: sum
		sourceColumn: turnover_margin

		annotation SummarizationSetBy = Automatic

	column off_epa_per_play_league_avg
		dataType: double
		lineageTag: 69774d1c-93f2-4375-a79a-3f4045938e2d
		summarizeBy: sum
		sourceColumn: off_epa_per_play_league_avg

		annotation SummarizationSetBy = Automatic

	column off_success_rate_league_avg
		dataType: double
		lineageTag: 5674e773-1dde-4143-abad-316a9779930b
		summarizeBy: sum
		sourceColumn: off_success_rate_league_avg

		annotation SummarizationSetBy = Automatic

	column off_third_down_pct_league_avg
		dataType: double
		lineageTag: 00aa01d3-0bed-4355-89c6-cc358e468356
		summarizeBy: sum
		sourceColumn: off_third_down_pct_league_avg

		annotation SummarizationSetBy = Automatic

	column off_turnovers_league_avg
		dataType: double
		lineageTag: 51959d71-9f85-4b95-b2a3-1bc483da1c48
		summarizeBy: sum
		sourceColumn: off_turnovers_league_avg

		annotation SummarizationSetBy = Automatic

	column off_penalties_league_avg
		dataType: double
		lineageTag: b68f5094-72a2-408b-b2f9-a6492079ed6f
		summarizeBy: sum
		sourceColumn: off_penalties_league_avg

		annotation SummarizationSetBy = Automatic

	column def_epa_per_play_allowed_league_avg
		dataType: double
		lineageTag: cf5caa4a-f67d-40c4-bf6e-3c029b6a1287
		summarizeBy: sum
		sourceColumn: def_epa_per_play_allowed_league_avg

		annotation SummarizationSetBy = Automatic

	column def_success_rate_allowed_league_avg
		dataType: double
		lineageTag: 9e18e7d0-8f89-4304-a97c-04c697944e14
		summarizeBy: sum
		sourceColumn: def_success_rate_allowed_league_avg

		annotation SummarizationSetBy = Automatic

	column def_third_down_pct_allowed_league_avg
		dataType: double
		lineageTag: 382578ab-901c-49f3-b784-669749129574
		summarizeBy: sum
		sourceColumn: def_third_down_pct_allowed_league_avg

		annotation SummarizationSetBy = Automatic

	column def_takeaways_league_avg
		dataType: double
		lineageTag: d3aed9e0-2531-42db-8909-c591f7e6001f
		summarizeBy: sum
		sourceColumn: def_takeaways_league_avg

		annotation SummarizationSetBy = Automatic

	column turnover_margin_league_avg
		dataType: double
		lineageTag: 945a6b6e-b073-424b-a1cb-b66b186eeaa7
		summarizeBy: sum
		sourceColumn: turnover_margin_league_avg

		annotation SummarizationSetBy = Automatic

	column win_pct_league_avg
		dataType: double
		lineageTag: f6eda5e1-2fce-44ca-b353-8e77eb1b6985
		summarizeBy: sum
		sourceColumn: win_pct_league_avg

		annotation SummarizationSetBy = Automatic

	partition bears_vs_league = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Ryan\Desktop\nfl-win-analytics\exports\bears_vs_league.csv"),[Delimiter=",", Columns=30, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"season", Int64.Type}, {"team", type text}, {"games_played", Int64.Type}, {"wins", Int64.Type}, {"losses", Int64.Type}, {"win_pct", type number}, {"points_per_game", type number}, {"points_allowed_per_game", type number}, {"point_differential", type number}, {"off_epa_per_play", type number}, {"off_success_rate", type number}, {"off_third_down_pct", type number}, {"off_turnovers", type number}, {"off_penalties", type number}, {"def_epa_per_play_allowed", type number}, {"def_success_rate_allowed", type number}, {"def_third_down_pct_allowed", type number}, {"def_takeaways", type number}, {"turnover_margin", type number}, {"off_epa_per_play_league_avg", type number}, {"off_success_rate_league_avg", type number}, {"off_third_down_pct_league_avg", type number}, {"off_turnovers_league_avg", type number}, {"off_penalties_league_avg", type number}, {"def_epa_per_play_allowed_league_avg", type number}, {"def_success_rate_allowed_league_avg", type number}, {"def_third_down_pct_allowed_league_avg", type number}, {"def_takeaways_league_avg", type number}, {"turnover_margin_league_avg", type number}, {"win_pct_league_avg", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

