table correlation_with_wins
	lineageTag: fca462e0-d576-47a9-a935-438291df5eb0

	column metric
		dataType: string
		lineageTag: 09169dd6-a952-48dd-bda3-0b06c17b10f1
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column correlation_with_win_pct
		dataType: double
		lineageTag: 4baaab8b-ffa2-47e7-ac50-a3c550e42cdf
		summarizeBy: sum
		sourceColumn: correlation_with_win_pct

		annotation SummarizationSetBy = Automatic

	partition correlation_with_wins = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Ryan\Desktop\nfl-win-analytics\exports\correlation_with_wins.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"metric", type text}, {"correlation_with_win_pct", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

