table linear_coefficients
	lineageTag: 306e2f61-e54e-450f-84a0-9442b6f55b85

	column metric
		dataType: string
		lineageTag: 5544dd1c-7693-4b84-8f41-4947e0e6ad94
		summarizeBy: none
		sourceColumn: metric

		annotation SummarizationSetBy = Automatic

	column standardized_coefficient
		dataType: double
		lineageTag: 75d3d1b9-14c9-4c3d-a682-56b88d4246e7
		summarizeBy: sum
		sourceColumn: standardized_coefficient

		annotation SummarizationSetBy = Automatic

	partition linear_coefficients = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Ryan\Desktop\nfl-win-analytics\exports\linear_coefficients.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"metric", type text}, {"standardized_coefficient", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

