table team_season_summary
	lineageTag: f3282b51-64d4-4fd8-87a7-f62d2beda043

	column team
		dataType: string
		lineageTag: 2860c168-e8c0-4f9f-8ade-973ce809f4ad
		summarizeBy: none
		sourceColumn: team

		annotation SummarizationSetBy = Automatic

	column season
		dataType: int64
		formatString: 0
		lineageTag: c734e7d4-9c1d-49b3-8cb1-518cf2b53c6a
		summarizeBy: sum
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column games_played
		dataType: int64
		formatString: 0
		lineageTag: a8f3361b-bcb7-47b1-837b-1f462d85b106
		summarizeBy: sum
		sourceColumn: games_played

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: a79223f4-5e42-4616-97df-c2737b8a53ed
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	column losses
		dataType: int64
		formatString: 0
		lineageTag: 1fb8d5bd-11ea-450e-8678-5bc7935738d1
		summarizeBy: sum
		sourceColumn: losses

		annotation SummarizationSetBy = Automatic

	column win_pct
		dataType: double
		lineageTag: 46b8f9a2-191c-4fcc-b803-8971a0577b9b
		summarizeBy: sum
		sourceColumn: win_pct

		annotation SummarizationSetBy = Automatic

	column points_per_game
		dataType: double
		lineageTag: d12d0df2-244a-4a08-aaef-c84a6ddc8cc0
		summarizeBy: sum
		sourceColumn: points_per_game

		annotation SummarizationSetBy = Automatic

	column points_allowed_per_game
		dataType: double
		lineageTag: 6a0b539b-6d75-4737-9142-5a4d791fc418
		summarizeBy: sum
		sourceColumn: points_allowed_per_game

		annotation SummarizationSetBy = Automatic

	column point_differential
		dataType: double
		lineageTag: 254c7820-5f47-45d1-9ca7-f9b436a4d151
		summarizeBy: sum
		sourceColumn: point_differential

		annotation SummarizationSetBy = Automatic

	column off_epa_per_play
		dataType: double
		lineageTag: 43b7fb71-1eb4-42b3-a470-1d41ebc28dd4
		summarizeBy: sum
		sourceColumn: off_epa_per_play

		annotation SummarizationSetBy = Automatic

	column off_success_rate
		dataType: double
		lineageTag: fc49b082-034a-493d-a31f-a18fda2be0ba
		summarizeBy: sum
		sourceColumn: off_success_rate

		annotation SummarizationSetBy = Automatic

	column off_third_down_pct
		dataType: double
		lineageTag: 7abf2c16-ff2d-41d9-aa1e-15b8d8332594
		summarizeBy: sum
		sourceColumn: off_third_down_pct

		annotation SummarizationSetBy = Automatic

	column off_turnovers
		dataType: double
		lineageTag: 0e667357-6afe-48f7-a5aa-821c8f89e89f
		summarizeBy: sum
		sourceColumn: off_turnovers

		annotation SummarizationSetBy = Automatic

	column off_penalties
		dataType: double
		lineageTag: da04bc3e-2b98-476d-b0ab-dad1c5e6aafb
		summarizeBy: sum
		sourceColumn: off_penalties

		annotation SummarizationSetBy = Automatic

	column def_epa_per_play_allowed
		dataType: double
		lineageTag: 5c183ee5-433b-4d00-b37e-5ccf82e608c4
		summarizeBy: sum
		sourceColumn: def_epa_per_play_allowed

		annotation SummarizationSetBy = Automatic

	column def_success_rate_allowed
		dataType: double
		lineageTag: a9676128-6e57-4aca-a77a-f255c4cfd446
		summarizeBy: sum
		sourceColumn: def_success_rate_allowed

		annotation SummarizationSetBy = Automatic

	column def_third_down_pct_allowed
		dataType: double
		lineageTag: 6efdb0fe-e316-42f7-8080-ee2b237e83fc
		summarizeBy: sum
		sourceColumn: def_third_down_pct_allowed

		annotation SummarizationSetBy = Automatic

	column def_takeaways
		dataType: double
		lineageTag: 6808bc31-ee68-4328-8a5e-81edbe64324f
		summarizeBy: sum
		sourceColumn: def_takeaways

		annotation SummarizationSetBy = Automatic

	column turnover_margin
		dataType: double
		lineageTag: 9110ca77-a76a-4f09-9215-9392bb8d3feb
		summarizeBy: sum
		sourceColumn: turnover_margin

		annotation SummarizationSetBy = Automatic

	measure 'Avg Win Pct' = AVERAGE(team_season_summary[win_pct])
		formatString: 0.0%
		lineageTag: a183b115-ff57-4add-9dd2-6aaccfd1617f

	measure 'Avg Off EPA per Play' = AVERAGE(team_season_summary[off_epa_per_play])
		formatString: 0.000
		lineageTag: 74227f89-fc12-4894-9054-913dcf97c402

	measure 'Avg Def EPA Allowed' = AVERAGE(team_season_summary[def_epa_per_play_allowed])
		formatString: 0.000
		lineageTag: 7c524064-b69a-49fa-9ecc-203b6153e993

	measure 'Total Wins' = SUM(team_season_summary[wins])
		formatString: 0
		lineageTag: f5a07774-883e-4cef-8fee-943475f64929

	measure 'Bears Win Pct' = CALCULATE([Avg Win Pct], team_season_summary[team] = "CHI")
		formatString: 0.0%
		lineageTag: a7683a11-5656-49b8-8fa5-f92ecc6fd070

	measure 'League Avg Off EPA' = CALCULATE([Avg Off EPA per Play], ALL(team_season_summary[team]))
		formatString: 0.000
		lineageTag: 44f6baea-6266-40b4-a166-a5b61b5ad6e4

	partition team_season_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Ryan\Desktop\nfl-win-analytics\exports\team_season_summary.csv"),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"team", type text}, {"season", Int64.Type}, {"games_played", Int64.Type}, {"wins", Int64.Type}, {"losses", Int64.Type}, {"win_pct", type number}, {"points_per_game", type number}, {"points_allowed_per_game", type number}, {"point_differential", type number}, {"off_epa_per_play", type number}, {"off_success_rate", type number}, {"off_third_down_pct", type number}, {"off_turnovers", type number}, {"off_penalties", type number}, {"def_epa_per_play_allowed", type number}, {"def_success_rate_allowed", type number}, {"def_third_down_pct_allowed", type number}, {"def_takeaways", type number}, {"turnover_margin", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
