table teams
	lineageTag: fba929ec-4e19-4417-bead-3ed02e6a3f92

	column team_abbr
		dataType: string
		lineageTag: 23e1b214-e35f-41d3-8475-7a38a8b38246
		summarizeBy: none
		sourceColumn: team_abbr

		annotation SummarizationSetBy = Automatic

	column team_name
		dataType: string
		lineageTag: 7d0f06a1-91ec-4ba0-bb63-1e6eececf34a
		summarizeBy: none
		sourceColumn: team_name

		annotation SummarizationSetBy = Automatic

	column team_nick
		dataType: string
		lineageTag: 27e9a6ca-bce1-4990-8b7a-1cd4eadf7515
		summarizeBy: none
		sourceColumn: team_nick

		annotation SummarizationSetBy = Automatic

	column team_conf
		dataType: string
		lineageTag: 4708cb80-7119-4faa-beac-f2347953ea0e
		summarizeBy: none
		sourceColumn: team_conf

		annotation SummarizationSetBy = Automatic

	column team_division
		dataType: string
		lineageTag: 54d9dcad-c546-4c67-979d-375cebb7656f
		summarizeBy: none
		sourceColumn: team_division

		annotation SummarizationSetBy = Automatic

	column team_color
		dataType: string
		lineageTag: 5a916fa3-80ae-4cb6-bff0-604a6c8f415f
		summarizeBy: none
		sourceColumn: team_color

		annotation SummarizationSetBy = Automatic

	column team_color2
		dataType: string
		lineageTag: 6030c08a-85f4-4751-8f08-eebce3afef15
		summarizeBy: none
		sourceColumn: team_color2

		annotation SummarizationSetBy = Automatic

	column team_logo_espn
		dataType: string
		lineageTag: c570c1c2-0145-4e96-b99b-e1e0d99c6085
		summarizeBy: none
		sourceColumn: team_logo_espn

		annotation SummarizationSetBy = Automatic

	partition teams = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Ryan\Desktop\nfl-win-analytics\exports\teams.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"team_abbr", type text}, {"team_name", type text}, {"team_nick", type text}, {"team_conf", type text}, {"team_division", type text}, {"team_color", type text}, {"team_color2", type text}, {"team_logo_espn", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

