table team_season_summary
	lineageTag: c733144c-80fc-4097-8123-fd83176c5e14

	measure 'Avg Win Pct' = AVERAGE(team_season_summary[win_pct])
		formatString: 0.0%
		lineageTag: d1bec0bd-bac2-47a0-a2e8-5402912939f0

	measure 'Avg Off EPA per Play' = AVERAGE(team_season_summary[off_epa_per_play])
		formatString: 0.000
		lineageTag: bcf87ffc-c88b-4ed9-a5ec-c524afa53a0d

	measure 'Avg Def EPA Allowed' = AVERAGE(team_season_summary[def_epa_per_play_allowed])
		formatString: 0.000
		lineageTag: dbbea7ce-4d1f-42e4-8c05-98770e6e041c

	measure 'Total Wins' = SUM(team_season_summary[wins])
		formatString: 0
		lineageTag: 52003d27-3d68-4e93-a264-a53ee1034324

	measure 'Bears Win Pct' = CALCULATE([Avg Win Pct], team_season_summary[team] = "CHI")
		formatString: 0.0%
		lineageTag: bbef3cb3-672d-4f5e-89f2-ad8401e3097c

	measure 'League Avg Off EPA' = CALCULATE([Avg Off EPA per Play], ALL(team_season_summary[team]))
		formatString: 0.000
		lineageTag: 8abe8858-378f-4d7b-b55e-a918c9e46a56

	column team
		dataType: string
		lineageTag: 674e7734-3cef-4500-b94f-5472f30a273b
		summarizeBy: none
		sourceColumn: team

		annotation SummarizationSetBy = Automatic

	column season
		dataType: int64
		formatString: 0
		lineageTag: 1ddba68e-f01e-499f-a9e2-a3c148560b96
		summarizeBy: sum
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column games_played
		dataType: int64
		formatString: 0
		lineageTag: 0b1b30a3-b8b0-4bdf-b362-889f2d8c70b6
		summarizeBy: sum
		sourceColumn: games_played

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: 375181a0-9605-4290-81e6-269c5144f3f1
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	column losses
		dataType: int64
		formatString: 0
		lineageTag: 8bef91f4-288a-442d-8a74-9afe288a7aa0
		summarizeBy: sum
		sourceColumn: losses

		annotation SummarizationSetBy = Automatic

	column win_pct
		dataType: double
		lineageTag: 9ab1bad4-b64d-4718-a8ba-4dab6fee77dc
		summarizeBy: sum
		sourceColumn: win_pct

		annotation SummarizationSetBy = Automatic

	column points_per_game
		dataType: double
		lineageTag: cbc931e5-f987-4d7f-b2aa-722dae625ce0
		summarizeBy: sum
		sourceColumn: points_per_game

		annotation SummarizationSetBy = Automatic

	column points_allowed_per_game
		dataType: double
		lineageTag: 311ffa9a-cf40-4b78-8b72-d5b491fb3c36
		summarizeBy: sum
		sourceColumn: points_allowed_per_game

		annotation SummarizationSetBy = Automatic

	column point_differential
		dataType: double
		lineageTag: 95e005b3-11aa-4778-ae99-1e1e47787c00
		summarizeBy: sum
		sourceColumn: point_differential

		annotation SummarizationSetBy = Automatic

	column off_epa_per_play
		dataType: double
		lineageTag: 94e15fbb-e1e6-4844-96c3-101c2d9ef892
		summarizeBy: sum
		sourceColumn: off_epa_per_play

		annotation SummarizationSetBy = Automatic

	column off_success_rate
		dataType: double
		lineageTag: 4cd2e68c-57c0-4c29-902b-966fc12d1d65
		summarizeBy: sum
		sourceColumn: off_success_rate

		annotation SummarizationSetBy = Automatic

	column off_third_down_pct
		dataType: double
		lineageTag: 6044e617-7070-4e35-a460-bd33c1fca700
		summarizeBy: sum
		sourceColumn: off_third_down_pct

		annotation SummarizationSetBy = Automatic

	column off_turnovers
		dataType: double
		lineageTag: 1bb2427b-91ee-4562-b80a-39dd46d85792
		summarizeBy: sum
		sourceColumn: off_turnovers

		annotation SummarizationSetBy = Automatic

	column off_penalties
		dataType: double
		lineageTag: 691b738d-65eb-4310-a192-7db5fc70737b
		summarizeBy: sum
		sourceColumn: off_penalties

		annotation SummarizationSetBy = Automatic

	column def_epa_per_play_allowed
		dataType: double
		lineageTag: e94221e2-7f83-4f79-9652-f70f47c4ea74
		summarizeBy: sum
		sourceColumn: def_epa_per_play_allowed

		annotation SummarizationSetBy = Automatic

	column def_success_rate_allowed
		dataType: double
		lineageTag: 2fb7ea1e-0a9a-4c67-9f59-d33cdd4d2084
		summarizeBy: sum
		sourceColumn: def_success_rate_allowed

		annotation SummarizationSetBy = Automatic

	column def_third_down_pct_allowed
		dataType: double
		lineageTag: 3032060b-bdf7-451f-9d2a-220659c97376
		summarizeBy: sum
		sourceColumn: def_third_down_pct_allowed

		annotation SummarizationSetBy = Automatic

	column def_takeaways
		dataType: double
		lineageTag: f734a9db-95a0-4e23-adea-c7b670a9d329
		summarizeBy: sum
		sourceColumn: def_takeaways

		annotation SummarizationSetBy = Automatic

	column turnover_margin
		dataType: double
		lineageTag: e5a1712e-be28-4b56-b420-70a97417270f
		summarizeBy: sum
		sourceColumn: turnover_margin

		annotation SummarizationSetBy = Automatic

	partition team_season_summary = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Ryan\Desktop\nfl-win-analytics\exports\team_season_summary.csv"),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"team", type text}, {"season", Int64.Type}, {"games_played", Int64.Type}, {"wins", Int64.Type}, {"losses", Int64.Type}, {"win_pct", type number}, {"points_per_game", type number}, {"points_allowed_per_game", type number}, {"point_differential", type number}, {"off_epa_per_play", type number}, {"off_success_rate", type number}, {"off_third_down_pct", type number}, {"off_turnovers", type number}, {"off_penalties", type number}, {"def_epa_per_play_allowed", type number}, {"def_success_rate_allowed", type number}, {"def_third_down_pct_allowed", type number}, {"def_takeaways", type number}, {"turnover_margin", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

